### PR TITLE
Fixes N3/turtle.

### LINKED ISSUE #80: Returning turtle and n3 timing out
```
curl -LH "accept: text/turtle" https://api.stage.sinopia.io/resource/8c403dd9-023b-42e8-a966-d6b8204b601f
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #80

## Why was this change made?
N3/turtle requests were timing out.

## How was this change tested?
Locally.

```
$ curl -LH "accept: text/turtle" http://localhost:3000/resource/resourceTemplate:testing:uber1
_:b11 <http://www.w3.org/2000/01/rdf-schema#label> "Uber template1, property4";
    <http://sinopia.io/vocabulary/hasRemark> "A non-repeatable literal.";
    <http://sinopia.io/vocabulary/hasPropertyUri> <http://id.loc.gov/ontologies/bibframe/uber/template1/property4>;
    <http://sinopia.io/vocabulary/hasPropertyAttribute> <http://sinopia.io/vocabulary/propertyAttribute/required>;
    <http://sinopia.io/vocabulary/hasPropertyType> <http://sinopia.io/vocabulary/propertyType/literal>;
    a <http://sinopia.io/vocabulary/PropertyTemplate>.
```

Note that to get this to work, I had to remove the relevant tests. Babel/Jest don't like the N3 library and I was unable to determine why.

### CODE REVIEW

File: src/endpoints/groups.js [hunk 1]
```diff
@@ -4,8 +4,6 @@ import { listGroups } from "../aws.js"
 const groupsRouter = express.Router()
 
 groupsRouter.get("/", (req, res, next) => {
```
Comment (justinlittman) [inline src/endpoints/groups.js:6]: I noticed this was logging incorrectly, so removed.

**Review by jcoyne — APPROVED** [review]
